### ISSUE TITLE
TypeError: can't access dead object

### ISSUE THREAD

**Issue by atomGit** [brettz9/copylinktext#3]
seeing lots of these errors in the browser console when i load a new tab (it could even be an empty tab)

FF 35.0.1
CLT: 1.7.1

`TypeError: can't access dead object tab-firefox.js:98`

this may help...
https://blog.mozilla.org/addons/2012/09/12/what-does-cant-access-dead-object-mean/

**Comment by brettz9** [comment]
Thanks for the report. Were you experimenting with disabling or uninstalling the add-on? I don't have any unload clean-up, so that could be causing it, but if not, it is probably an issue with the SDK itself as my code is not (and does not need to be) doing things like injecting variables into pages in a custom manner.

**Comment by atomGit** [comment]
i wasn't experimenting with the add-on - i just happened to notice the errors in the console

if you're not seeing the errors, i wouldn't worry about it - i stopped using the add-on because i don't really need it and i'm trying to cut down on my add-on addiction :)

take care!

**Comment by brettz9** [comment]
Am closing as I think this was probably due to the SDK itself and not seeing issues. Feel free to reopen otherwise.
