### ISSUE TITLE
excessive memory usage

### ISSUE THREAD

**Issue by atomGit** [brettz9/copylinktext#6]
CLT 1.7.1
FF 37.0.1
WIN 7

i stopped using the extension since i really don't need it, but when i checked about:memory, it indicated that CLT was using over 20 MB of memory

**Comment by brettz9** [comment]
I have added this as a to-do to investigate though I'm not sure when/if I'll get to it. It does seem the memory goes up upon each usage (though memory does seem cleared at least when closing the tab). I'm not sure whether this is due to FF's SDK (in which case I can do nothing besides report the bug or revert to my old non-SDK version) or due to my own usage of it. Anyways, thanks for the report.

**Comment by brettz9** [comment]
I am not seeing this at all, using `about:addons-memory`, and I think if there were an issue, it would really be due to the SDK. Closing for now, but feel free to resubmit if you come back to the add-on and still find the issue. Thanks for the report!
