### ISSUE TITLE
Missing from right menu context

### ISSUE THREAD

**Issue by BurkeKnight** [brettz9/copylinktext#7]
It would appear that one of the comments is confirmed, for me, at least. Firefox 37.0.2
It was working fine, then noticed today, that Copy Link Text was missing from menu.
Tried uninstalling, then reinstalling, and still missing. No new addons installed.

**Comment by brettz9** [comment]
Try upgrading to Firefox 38

**Comment by BurkeKnight** [comment]
I would, if it did not state "Firefox is up to date"
I wonder why it's not finding the update.

**Comment by brettz9** [comment]
Odd--for now, I think you should be able to go to https://addons.mozilla.org/en-US/firefox/addon/copy-link-text-4750/versions/ and download the older version 1.7.1.1. Then you go to about:addons (or Tools->Add-ons), click "More", and on the new page that shows up, change "Automatic Updates" to "Off". Periodically check your Firefox version and after it updates to 38, put the auto-updates back on.

**Comment by Ambaquista** [comment]
Since Firefox 37, this extension didn´t work! I disable, remove and re-install, but nothing! Today with Firefox 39, I tried again with no sucess
Any idea?
B rgds

**Comment by brettz9** [comment]
@Ambaquista , are you using a menu editing program like Menu Editor or Menu Wizard?

**Comment by Ambaquista** [comment]
No.

My list of using extensios:
2 Pane Bookmarks
Add-on Compatibility Report
AddMoreTextToC1ipboard
All-in-One Sidebar
Clip title url active tab
Copy Link Text
Disconnect
DownThemAll!
EPUBReader
GrabMyBooks
IE View
ImTranslator
Mozilla Archive Format
NoScript
QuickFox Notes
QuickWiki
ReminderFox
Save File to
5crapBook
UnMHT
UnPlug
Video DownloadHelper
ViewSourceWith

Thank you for your support
BRgds

On Sat, Jul 4, 2015 at 2:47 AM, Brett Zamir <notifications@github.com>
wrote:

> @Ambaquista <https://github.com/Ambaquista> , are you using a menu
> editing program like Menu Editor or Menu Wizard?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brettz9/copylinktext/issues/7#issuecomment-118449355>.
>



-- 
Carlos Alberto Carranca
ccarranca@gmail.com
carlos.carranca@flytaag.com
024 924360875
024 222335852
024 226421001 * 121130

**Comment by brettz9** [comment]
Are you on a Mac or what? Also, you might try disabling all of your other extensions, and see if the problem persists. If not, you can then try re-enabling half of your extensions, and keep adding a half more until it fails, and then disable some again until you isolate the add-on at fault.

**Comment by Ambaquista** [comment]
Sorry, my system: Windows 7 Professional (x64) Service Pack 1 (build 7601)
Ok, I will try your sugestion
Thanks again
BRgds

On Sun, Jul 5, 2015 at 4:11 AM, Brett Zamir <notifications@github.com>
wrote:

> Are you on a Mac or what? Also, you might try disabling all of your other
> extensions, and see if the problem persists. If not, you can then try
> re-enabling half of your extensions, and keep adding a half more until it
> fails, and then disable some again until you isolate the add-on at fault.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brettz9/copylinktext/issues/7#issuecomment-118573916>.
>



-- 
Carlos Alberto Carranca
ccarranca@gmail.com
carlos.carranca@flytaag.com
024 924360875
024 222335852
024 226421001 * 121130

**Comment by swardman** [comment]
The context menu item does not appear for me with Copy Link Text 1.7.2 from addons.mozilla.org on Firefox ESR 31.8.0 on Windows 7 Professional (x64) SP1. The context menu item does appear in Firefox Developer Edition 41.0a2 (2015-07-23). I don't have a release channel version handy to test right now.

I also tested the following on FF ESR 31.8.0:
1.6.3.1-signed -- doesn't work
1.5.3.1-signed -- works

It might be a red herring, but 1.5.3.1 is the last version on a.m.o before the restart less version.

**Comment by brettz9** [comment]
Thank you, @swardman for the helpful and detailed testing with environment information. It has been working fine for me on other Firefox versions like the main release and Nightly, but good to be reminded about the existence of ESR and why this may be a problem for some users.

I made the changes to provide users with the restartless ability as well as work in the manner that Firefox recommends, via the SDK (i.e., the add-on format which provides the restartless ability)--which regrettably seems to cause problems for those on older versions even though my add-on is quite simple. If there is a way to get this to work on older versions (probably would be a packaging issue if you find other SDK add-ons that do work), I'm open to learning about it, but I have limited energy (due to poor health) to work on exploring this further.

In the meantime, you can disable updates on individual add-ons which I would recommend doing in this case (there have been no critical security fixes, and there should be no problems in disabling the updates for this add-on, though I would recommend checking back when you can use an up-to-date version of Firefox). In the current version of Firefox at least, after installing a version of CopyLinkText that works for you, just go to "about:addons", double-click my add-on, and set "Automatic updates" to "Off". There are also details at http://kb.mozillazine.org/Updating_extensions#Disabling_update_checks_for_individual_add-ons_-_Advanced_users in case this doesn't work on older versions.

I know you tested without other add-ons, but for completeness' sake, I will also mention here for others that users have found problems using my add-on with Menu Editor or Menu Wizard, but that is because of those add-ons depending on menu IDs, and my add-on cannot add these in a convenient way via the SDK (though I could work around that particular issue if Firefox implements https://bugzilla.mozilla.org/show_bug.cgi?id=956461 ).

Also, other users, please try to use the latest version of Firefox.

**Comment by Ambaquista** [comment]
Well, no news, bad news...
I tried several versions (1.5.3.1-signed to 1.7.2  No Restart), with and without restarting Firefox 39, etc and the extension does not appear in the context menu.
After the CopyURL+ stoped working, its now the time to CopyLinkText? Too bad!
b rgds

**Comment by brettz9** [comment]
When using Firefox 39, did you try disabling all your other extensions and then reenable Copy Link Text? CopyURL appears to also be restartless, so it would make sense that it is not working in older Firefox at least. This is almost certainly not the fault of our add-ons--which are very simple...

**Comment by Ambaquista** [comment]
Nice surprise today!
In Firefox 40.0.2, CoLT 2.6.5,1 works as before!
Thanks, good work.
b rgds

**Comment by brettz9** [comment]
@Ambaquista : I think you have the wrong add-on. CoLT is a different add-on: https://addons.mozilla.org/en-us/firefox/addon/colt/ . Mine is similar, but at https://addons.mozilla.org/en-US/firefox/addon/copy-link-text-4750/

**Comment by brettz9** [comment]
I am closing as this seems to be exclusively an older Firefox issue and/or usage of a different add-on or interaction with menu editing programs.

**Comment by brettz9** [comment]
Spoke too soon--it has been working--and now I notice it isn't!  Ugh... Probably some breaking change by FF again... :( will investigate...

**Comment by brettz9** [comment]
I see my test environment is FF 43 alpha, and it is working fine there. FF 42 beta also works (though not in private windows). Maybe it is the latest jpm packager which bundles the add-ons is broken for older versions of Firefox, but as I don't have energy to deal with this, I'm still going to consider the issue resolved since it should be working again once Firefox releases the upgrades. Sorry for the trouble!
